const questions = [
  {
    id: 1,
    text: "Vai jūs dodat priekšroku darbam komandā vai individuāli?",
    type: "scale",
    min: 0,
    max: 10,
    minLabel: "Individuāli",
    maxLabel: "Komandā",
    field: "teamwork_preference",
  },
  {
    id: 2,
    text: "Cik svarīga jums ir iespēja darba laikā iemācīties jaunas prasmes?",
    type: "scale",
    min: 0,
    max: 10,
    minLabel: "Nav svarīgi",
    maxLabel: "Ļoti svarīgi",
    field: "learning_opportunity",
  },
  {
    id: 3,
    text: "Cik gadu darba pieredze jums ir?",
    type: "multiple",
    options: [
      { value: 0, text: "Nav pieredzes" },
      { value: 3, text: "1-3 gadi" },
      { value: 6, text: "4-7 gadi" },
      { value: 10, text: "8+ gadi" },
    ],
    field: "experience_required",
  },
  {
    id: 4,
    text: "Kāda darba vide jums vislabāk patīk?",
    type: "multiple",
    options: [
      { value: 0, text: "Klusa un koncentrēta" },
      { value: 3, text: "Mēreni interaktīva" },
      { value: 7, text: "Dinamiska un sadarbīga" },
      { value: 10, text: "Ļoti sociāla un komunikatīva" },
    ],
    field: "work_environment",
  },
  {
    id: 5,
    text: "Kā jūs tiekat galā ar saspringtu darbu un termiņiem (deadlines)?",
    type: "scale",
    min: 0,
    max: 10,
    minLabel: "Dodu priekšroku atslābinātam darbam",
    maxLabel: "Saspringtā vidē strādāju vislabāk",
    field: "stress_level",
  },
  {
    id: 6,
    text: "Cik jums svarīga ir iespēja darbā būt radošam?",
    type: "scale",
    min: 0,
    max: 10,
    minLabel: "Nav svarīga",
    maxLabel: "Ļoti svarīga",
    field: "creativity_required",
  },
  {
    id: 7,
    text: "Vai jūs dotu priekšroku darbam lielā vai mazā uzņēmumā?",
    type: "multiple",
    options: [
      { value: 0, text: "Man vienalga" },
      { value: 3, text: "Mazā uzņēmumā (līdz 20 darbiniekiem)" },
      { value: 5, text: "Vidēja izmēra uzņēmumā (20-100 darbinieki)" },
      { value: 7, text: "Lielā (100-500 darbinieki)" },
      { value: 10, text: "Ļoti lielā (500+ darbinieki)" },
    ],
    field: "company_size",
  },
  {
    id: 8,
    text: "Vai labprāt strādājat attālināti?",
    type: "multiple",
    options: [
      { value: 0, text: "Nē, dodu priekšroku darbam birojā" },
      {
        value: 5,
        text: "Vislabāk patīk hidrīds režīms (gan birojā, gan attālināti)",
      },
      { value: 10, text: "Labprāt strādāju pilnībā attālināti" },
    ],
    field: "remote_preference",
  },
  {
    id: 9,
    text: "Cik svarīgas jums ir karjeras izaugsmes iespējas?",
    type: "scale",
    min: 0,
    max: 10,
    minLabel: "Nav svarīgi",
    maxLabel: "Ļoti svarīgi",
    field: "career_growth",
  },
  {
    id: 10,
    text: "Kāda veida projektos jūs vēlētos strādāt?",
    type: "multiple",
    options: [
      { value: 2, text: "Ilgos, stabilos projektos (ne īsāki par gadu)" },
      { value: 5, text: "Vidēji ilgos projektos (3-12 mēneši)" },
      { value: 8, text: "Īsos projektos (1-3 mēneši)" },
      {
        value: 10,
        text: "Eksperimentālos, inovatīvos projektos (līdz mēnesim)",
      },
    ],
    field: "project_type",
  },
];
