// Define the questions for the job matcher
const questions = [
  {
    id: 1,
    text: "Do you prefer working in a team or individually?",
    type: "scale", // This will be rendered as a slider
    min: 0,
    max: 10,
    minLabel: "Individually",
    maxLabel: "Team",
    field: "work_environment", // This corresponds to the field in jobs.json
  },
  {
    id: 2,
    text: "How tech-savvy are you?",
    type: "scale",
    min: 0,
    max: 10,
    minLabel: "Not tech-savvy",
    maxLabel: "Very tech-savvy",
    field: "tech_level",
  },
  {
    id: 3,
    text: "How much work experience do you have?",
    type: "multiple",
    options: [
      { value: 0, text: "No experience" },
      { value: 3, text: "1-3 years" },
      { value: 6, text: "4-7 years" },
      { value: 10, text: "8+ years" },
    ],
    field: "experience_required",
  },
  {
    id: 4,
    text: "What type of work environment do you prefer?",
    type: "multiple",
    options: [
      { value: 0, text: "Quiet and focused" },
      { value: 3, text: "Moderately interactive" },
      { value: 7, text: "Dynamic and collaborative" },
      { value: 10, text: "Highly social and communicative" },
    ],
    field: "work_environment",
  },
  {
    id: 5,
    text: "How do you handle work pressure and deadlines?",
    type: "scale",
    min: 0,
    max: 10,
    minLabel: "I prefer low pressure",
    maxLabel: "I thrive under pressure",
    field: "stress_level",
  },
  {
    id: 6,
    text: "How important is creativity in your ideal job?",
    type: "scale",
    min: 0,
    max: 10,
    minLabel: "Not important",
    maxLabel: "Very important",
    field: "creativity_required",
  },
  {
    id: 7,
    text: "What's your preferred salary range?",
    type: "multiple",
    options: [
      { value: 0, text: "I'm flexible" },
      { value: 3, text: "Up to 1500 EUR" },
      { value: 5, text: "1500-2500 EUR" },
      { value: 7, text: "2500-4000 EUR" },
      { value: 10, text: "4000+ EUR" },
    ],
    field: "salary_expectation",
  },
  {
    id: 8,
    text: "Are you looking for remote work opportunities?",
    type: "multiple",
    options: [
      { value: 0, text: "No, I prefer on-site" },
      { value: 5, text: "Hybrid would be ideal" },
      { value: 10, text: "Yes, fully remote" },
    ],
    field: "remote_preference",
  },
  {
    id: 9,
    text: "How important is work-life balance to you?",
    type: "scale",
    min: 0,
    max: 10,
    minLabel: "Not a priority",
    maxLabel: "Top priority",
    field: "work_life_balance",
  },
  {
    id: 10,
    text: "Which type of company culture do you prefer?",
    type: "multiple",
    options: [
      { value: 2, text: "Traditional and structured" },
      { value: 5, text: "Professional and balanced" },
      { value: 8, text: "Modern and flexible" },
      { value: 10, text: "Innovative and casual" },
    ],
    field: "company_culture",
  },
];
